version: "3.9"

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: rp-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - /Users/TanPN/Documents/nginx-logs:/var/log/nginx
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
    external: true
